config/routes.rb
Rails.application.routes.draw do
  #get '/' => 'films#index'

	  resources :films
	  	root "films#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:titre, :date, :description, :genre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.erb
<%= form_for(film) do |f| %>
  <% if film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %>
    <%= f.text_field :titre %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<div class="containt">
  <div class="new">
<h2>Editing Film</h2>

<%= render 'form', film: @film %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>
  </div>
</div>

app/views/films/index.html.erb
<h1 id="titre">Liste de films à voir selon vous :</h1>

<table>
  <thead>
    <div class="bonjour">
    <tr>
      <th>Titre</th>
      <th class="date">Date de sortie</th>
      <th>Synopsis</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </div>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= film.titre %></td>
        <td><%= film.date %></td>
        <td class="describe"><%= film.description %></td>
        <td><%= film.genre %></td>
        <td><%= link_to 'Voir', film %></td>
        <td><%= link_to 'Modifier', edit_film_path(film) %></td>
        <td><%= link_to 'Supprimer', film, method: :delete, data: { confirm: 'Vous êtes sûrs de vouloir supprimer ce film de la liste?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="ajouter">
<%= link_to 'Ajoutez un film', new_film_path %>
</div>

app/views/films/new.html.erb
<div class="containt">
  <div class="new">
<h2> Nouveau Film </h2>

<%= render 'form', film: @film %>

<%= link_to 'Back', films_path %>
  </div>
</div>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titre:</strong>
  <%= @film.titre %>
</p>

<p>
  <strong>Date:</strong>
  <%= @film.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @film.description %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @film.genre %>
</p>

<%= link_to 'Edit', edit_film_path(@film) %> |
<%= link_to 'Back', films_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>